### ISSUE TITLE
Filesystem include issue

### ISSUE THREAD

**Issue by no-realm** [vector-of-bool/pitchfork#2]
In the file `src/pf/fs.hpp` you differentiate between **experimental** and **non-experimental** versions of the *filesystem* include.
I have noticed that your **else* branch is wrong:
```c++
#if STD_FS_IS_EXPERIMENTAL
#include <experimental/filesystem>
namespace pf {

namespace fs = std::experimental::filesystem;

}  // namespace pf
#else
#include <filesystem>
namespace pf {

namespace fs = std::experimental::filesystem;

}  // namespace pf
#endif
```

It should be: `namespace fs = std::filesystem;`
instead of: `namespace fs = std::experimental::filesystem;`

**Comment by vector-of-bool** [comment]
Good eye

**Comment by vector-of-bool** [comment]
Fixed
